# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putian', '0002_lunbo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('miaoshu', models.CharField(max_length=100)),
                ('pricename', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Content2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('miaoshu', models.CharField(max_length=100)),
                ('pricename', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
