# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putian', '0004_content3_content4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('backgroundimg', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('idnamm', models.CharField(max_length=100)),
            ],
        ),
    ]
