# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-11 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('putian', '0005_content5'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('qqname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
    ]
